// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjwpejhbwjbbkgxsfhnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqd3Blamhid2piYmtneHNmaG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODE0OTIsImV4cCI6MjA1ODE1NzQ5Mn0.aKHWSXkuTmUCkpbgU5lJ-wg3ipq_-gFoC6YBJCXu9Tw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);